import { MainCategory } from "./types";

export const mediaCategories: MainCategory[] = [
  {
    name: "VIDEO & MULTIMEDIA",
    emoji: "🎬",
    description: "AI-powered video creation, editing, and multimedia production tools",
    subcategories: [
      // Core video categories
      "Video Tools",
      "Video Generation Tools", 
      "Video Editing Tools",
      "Advanced Video Tools",
      "Video & Content Tools",
      "Video Editing & Content Tools",
      "Video Marketing Tools",
      "Video Business Tools",
      "Entertainment Media Tools",
      "Video And Content Tools",
      "Video Editing And Content Tools",
      "Video & Content Creation",
      "Video Generation",
      "Video Editing",
      "Video Marketing",
      "Video Business",
      "Multimedia",
      "Multimedia Tools",
      "Content Creation",
      "Entertainment Tools",
      "Creative Tools",
      "Creative Platforms",
      "Creative Services",
      "Creative Suites",
      "Entertainment Media Tools",
      "Creative And Entertainment",
      "Entertainment & Media",
      "Media Tools",
      "Media & Content",
      "Movie Tools",
      "Film Tools",
      "Cinema Tools",
      "Animation Tools",
      // Additional video-related categories that might exist
      "Video Creation",
      "Video Production",
      "Video Synthesis",
      "Video AI",
      "AI Video",
      "Text-to-Video",
      "Image-to-Video",
      "Video Enhancement",
      "Video Processing",
      "Video Automation",
      "Video Content",
      "Video Platforms",
      "Video Generation Platforms",
      "Creative Video Tools",
      "Professional Video Tools",
      "Video Creation Tools",
      "Video Technology",
      "Video Software",
      "Video Applications",
      "Cinematic Tools",
      "Motion Graphics",
      "Visual Effects",
      "Video Effects",
      "Multimedia & Content",
      "Content Creation Tools",
      "Content Creation And Writing Tools",
      "Creative Design Tools",
      "Raw & Uncut Tools"
    ]
  },
  {
    name: "AUDIO & VOICE TOOLS",
    emoji: "🎵",
    description: "AI tools for audio processing, voice synthesis, music generation, and sound editing",
    subcategories: [
      "Audio & Voice Tools",
      "Audio Music Tools",
      "Transcription & Document Tools",
      "Meeting & Transcription Tools",
      "Document And Research Tools",
      "Transcription And Document Tools",
      "Audio Tools",
      "Voice Tools",
      "Music Tools",
      "Audio Generation",
      "Voice Synthesis",
      "Music Generation",
      "Audio Processing",
      "Sound Effects",
      "Audio Enhancement"
    ]
  },
  {
    name: "3D & VISUALIZATION",
    emoji: "🧊",
    description: "AI tools for 3D modeling, visualization, and immersive content creation",
    subcategories: [
      // Core 3D categories
      "3D & Visualization Tools",
      "ThreeD And Visualization Tools",
      "3D Tools",
      "Visualization Tools",
      "3D Modeling",
      "3D Generation",
      "3D Design",
      "Virtual Reality",
      "Augmented Reality",
      "3D Animation",
      "3D Rendering",
      "3D Visualization",
      "Mixed Reality",
      "Extended Reality",
      "XR Tools",
      "VR Tools",
      "AR Tools",
      "MR Tools",
      "Immersive Experience",
      "Interactive 3D",
      "3D Web",
      "Text-to-3D",
      "Image-to-3D",
      "AI 3D Generation",
      "3D Art",
      "3D Graphics",
      "3D Models",
      "3D Assets",
      "3D Content",
      "3D Creation",
      "3D Development",
      "3D Technology",
      "3D Software",
      "3D Applications",
      "3D Platforms",
      "Volumetric Rendering",
      "Ray Tracing",
      "Real-time Rendering",
      "Physics Simulation",
      "Fluid Simulation",
      "Particle Systems",
      "Lighting Simulation",
      "Material Design",
      "Texture Generation",
      "Surface Modeling",
      "Mesh Generation",
      "Point Cloud Processing",
      "Photogrammetry",
      "LiDAR Processing",
      "Holographic Display",
      "CAD Tools",
      "Architecture Tools",
      "Engineering Tools",
      "Product Design",
      "Industrial Design",
      "Automotive Design",
      "Medical Visualization",
      "Scientific Visualization",
      "Data Visualization",
      "Information Visualization",
      "Interactive Visualization"
    ]
  }
];
