// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://huupailptzvcykyqdkar.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imh1dXBhaWxwdHp2Y3lreXFka2FyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg5MTMzODIsImV4cCI6MjA2NDQ4OTM4Mn0.IEqsLF3r-cyubqwwHOpkbSzz_IGt6v1U6LxO5fowHcQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});